### ISSUE TITLE
Compile problem with Image

### ISSUE THREAD

**Issue by alltonp** [remithomas/bs-react-native-elements#4]
Hi,

Appreciate this is WIP, so apologies if reporting issues is annoying... with the latest version I'm getting:

```
File "/Users/xxxxx/dev/my-app/node_modules/bs-react-native-elements/src/Elements_Image.re", line 37, characters 12-13:
Error: syntax error, consider adding a ';' before

  We've found a bug for you!
  /Users/xxxxx/dev/my-app/node_modules/bs-react-native-elements/src/Elements_Image.re
```  

As a workaround, I commented out `fromImageProps` to get it compiling.

**Comment by remithomas** [comment]
Hey this is not annoying, I gonna to take care of that.
thank you so much for the report 🤗

**Comment by remithomas** [comment]
@alltonp if you reinstall with the latest version, it should be fixed
